### PR TITLE
Update documentation about mode, remove unused param

### PR DESCRIPTION
**Pull request by hariso**
### Description

1. Updates documentation about operation mode (cdc, snapshot)
2. Removes unused `replication_url` parameter.

### Quick checks:

- [x] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [x] There is no other [pull request](https://github.com/ConduitIO/conduit-connector-postgres/pulls) for the same update/change.
- [ ] I have written unit tests. -- not needed
- [x] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

**Comment by hariso** [comment]
I just noticed https://github.com/ConduitIO/conduit-connector-postgres/issues/2. If there's much more planned work on updating the ReadMe than it's in this PR, we can close this one.

**Comment by lovromazgon** [comment]
There is probably more work needed here, let's postpone this a bit and get back to it in a week or two.

**Review by dylanlott — APPROVED** [review]
I updated the default values for the slot and publication name, too. LGTM.

**Comment by hariso** [comment]
> I updated the default values for the slot and publication name, too. LGTM.

💪

**Pull request merged**
